#!/bin/bash
set -e

cd "$(dirname "$0")"

# ─── Cloud platform detection ─────────────────────────────────────────────────
# start.sh is for local Docker only. Cloud platforms handle deployment natively.
if [ -n "$RAILWAY_ENVIRONMENT" ] || [ -n "$RENDER_SERVICE_ID" ] || [ -n "$FLY_APP_NAME" ]; then
  echo "Cloud platform detected — start.sh is not needed here."
  echo "The app will start automatically using the platform's configuration."
  exit 0
fi

# ─── Check prerequisites ──────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo ""
  echo "Error: Docker is not installed."
  echo "Install Docker: https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker compose version &>/dev/null; then
  echo "Error: Docker Compose is not available."
  echo "Install Docker Compose: https://docs.docker.com/compose/install/"
  exit 1
fi

# ─── First-run setup ─────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  echo ""
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║           First-Time Setup                              ║"
  echo "╚══════════════════════════════════════════════════════════╝"
  echo ""

  # Generate a secure random password
  GENERATED_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

  echo "  A secure database password has been generated for you."
  echo ""
  read -p "  Use generated password? [Y/n]: " USE_GENERATED
  USE_GENERATED=${USE_GENERATED:-Y}

  if [[ "$USE_GENERATED" =~ ^[Nn] ]]; then
    while true; do
      read -sp "  Enter a database password (min 12 chars): " POSTGRES_PASSWORD
      echo ""
      if [ ${#POSTGRES_PASSWORD} -lt 12 ]; then
        echo "  Password must be at least 12 characters. Try again."
      else
        break
      fi
    done
  else
    POSTGRES_PASSWORD="$GENERATED_PW"
    echo "  Password: $POSTGRES_PASSWORD"
    echo "  (saved to .env — keep this file safe)"
  fi

  echo ""

  # Generate a Redis password too
  REDIS_PW=$(openssl rand -base64 16 | tr -d '/+=' | head -c 20)

  # Create .env from example with the real passwords
  cat > .env <<EOF
# ─── Generated by start.sh on $(date +%Y-%m-%d) ──────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
REDIS_PASSWORD=${REDIS_PW}

# ─── Anthropic (set via setup wizard or here) ────────────────────────────────
ANTHROPIC_API_KEY=

# ─── Optional ────────────────────────────────────────────────────────────────
# POSTGRES_DB=ai_remote_service
# POSTGRES_USER=postgres
# POSTGRES_PORT=5432
# REDIS_PORT=6379
# API_PORT=8080
# WEB_PORT=3000
# API_URL=http://your-server-ip:8080
# FRONTEND_URL=http://localhost:3000
# GITHUB_REPO=Gaaldaco/ai-rmm-docker
EOF

  chmod 600 .env
  echo "  .env file created with secure permissions."
  echo ""
fi

# ─── Validate required env vars ──────────────────────────────────────────────
source .env 2>/dev/null || true

if [ -z "$POSTGRES_PASSWORD" ]; then
  echo "Error: POSTGRES_PASSWORD is not set in .env"
  echo "Run: rm .env && ./start.sh to re-run setup"
  exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║         Starting AI Remote Service Stack...             ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

docker compose up -d --build

WEB_PORT=$(grep "^WEB_PORT=" .env 2>/dev/null | cut -d'=' -f2 || echo "3000")
WEB_PORT=${WEB_PORT:-3000}

echo ""
echo "  All services started!"
echo ""
echo "  Open http://localhost:${WEB_PORT} in your browser."
echo "  If this is your first time, a setup wizard will guide you."
echo ""
echo "  Logs:  docker compose logs -f"
echo "  Stop:  docker compose down"
echo ""
